services:
  jidogam:
    container_name: jidogam-service
    image: yerimyeon/jidogam:latest
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - JVM_OPTS=-Xmx512m -Xms256m -XX:MaxMetaspaceSize=256m
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    volumes:
      - ./logs:/var/log/jidogam
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080${MGMT_PATH:-/actuator}/health || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - jidogam-network

  nginx:
    container_name: nginx
    image: nginx:1.26-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -t && nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - jidogam
    networks:
      - jidogam-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  jidogam-network:
    driver: bridge