services:
  app:
    container_name: jidogam-service
    image: jidogam/jidogam:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - JVM_OPTS=-Xmx512m -Xms256m -XX:MaxMetaspaceSize=256m
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    logging: ## logback 설정 전 임시 사용
      driver: json-file
      options:
        max-size: "50m"   # 파일 하나당 최대 50MB
        max-file: "3"     # 최대 3개 파일 (총 150MB)