spring:
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    region.jidogam: INFO
    org.springframework: INFO
    org.hibernate.sql: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO